### ISSUE TITLE
Enabling Livemap on dashboard causes "Login attempt or request with invalid authentication" warning.

### ISSUE THREAD

**Issue by AndreCox** [And3rsL/Deebot-for-Home-Assistant#143]
**Description**
When live map is enabled on dashboard through the Vacuum Card it sometimes causes a "Login attempt or request with invalid authentication" warning originating from the IP address of the device login in. This is related to the live map feature as when I remove it from the dashboard the error goes away. I also believe that for this issue to happen the live map must be visible on the first page that loads when you log into home assistant although I need to test this further.
 

**Configuration**

```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
    server_port: 8123
    use_x_forwarded_for: true
    trusted_proxies: 
    - 192.168.1.253
    ip_ban_enabled: true
    login_attempts_threshold: 3
    
duckdns:
  access_token: my-token
  domain: my-domain.com
  
google_assistant:
  project_id: my-project-id
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

# Text to speech
tts:
  - platform: google_translate
    cache: true
    language: 'en'
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.56
    port: 5005
  - platform: yamaha_musiccast
    host: 192.168.1.57
    port: 5006
  - platform: mpd
    name: 'Living Room TTS'
    host: 192.168.1.78
    

discovery:

conversation:

frontend:
  themes: !include_dir_merge_named themes

mqtt:
  discovery: true
  discovery_prefix: homeassistant

sensor:
  - platform: mqtt
    name: SDS011 2.5
    state_topic: "/homeassistant/weather/particulatematter"
    value_template: '{{ value_json.pm25 }}'
    unit_of_measurement: µg/m³

  - platform: mqtt
    name: SDS011 10
    state_topic: "/homeassistant/weather/particulatematter"
    value_template: '{{ value_json.pm10 }}'
    unit_of_measurement: µg/m³

  - platform: average
    name: Average PM 2.5
    duration: 
      days: 1
    entities: 
        - sensor.sds011_2_5
    
  - platform: average
    name: Average PM 10
    duration: 
      days: 1
    entities: 
        - sensor.sds011_10
        
  - platform: mqtt  
    state_topic: "shellies/leaksensor1/sensor/temperature"  
    name: "Flood Sensor 1 Temp"  
    unit_of_measurement: "°C"  
  - platform: mqtt  
    state_topic: "shellies/leaksensor1/sensor/battery"  
    name: "Flood Sensor 1 Battery"  
    unit_of_measurement: "%"  
    device_class: battery

  - platform: mqtt  
    state_topic: "shellies/leaksensor2/sensor/temperature"  
    name: "Flood Sensor 2 Temp"  
    unit_of_measurement: "°C"  
  - platform: mqtt  
    state_topic: "shellies/leaksensor2/sensor/battery"  
    name: "Flood Sensor 2 Battery"  
    unit_of_measurement: "%"  
    device_class: battery
    
binary_sensor:
    - platform: mqtt
      name: "Flood Sensor 1"
      state_topic: "shellies/leaksensor1/sensor/flood"
      qos: 2
      payload_on: "true"
      payload_off: "false"
      device_class: moisture
    
    - platform: mqtt
      name: "Flood Sensor 2"
      state_topic: "shellies/leaksensor2/sensor/flood"
      qos: 2
      payload_on: "true"
      payload_off: "false"
      device_class: moisture
        
switch:
  - platform: mqtt
    name: "Projector"
    state_topic: "mediaroom/OpenMQTTGateway/IRtoMQTT"
    command_topic: "mediaroom/OpenMQTTGateway/commands/MQTTtoIR"
    payload_on: '{"value":848397,"protocol_name":"NEC","repeat":25,"bits":32}'
    payload_off: '{"value":815757,"protocol_name":"NEC","repeat":25,"bits":32}'
    optimistic: false
    retain: false
    
  - platform: mqtt
    name: "Projector Screen"
    state_topic: "mediaroom/OpenMQTTGateway/IRtoMQTT"
    command_topic: "mediaroom/OpenMQTTGateway/commands/MQTTtoIR"
    payload_on: '{"raw":"6660,4816,1492,314,776,680,404,314,778,684,404,316,776,680,404,314,778,678,406,320,776,678,404,316,776,678,406,314,778,678,404,314,778,678,406,322,776,678,406,320,776,680,404,316,776,678,406,314,778,678,406,322,776,676,408,314,776,680,404,314,778,678,406,314,778,678,406,324,774,322,776,678,406,678,404,314,778,314,778,678,404,678,404,12140,6660,4816,1490,322,776,678,406,314,778,678,406,314,776,678,404,316,776,678,406,320,776,680,404,314,778,678,404,314,776,678,406,314,776,684,406,320,776,678,406,314,778,678,404,316,776,678,406,314,776,678,406,322,776,680,404,314,778,678,406,314,778,678,404,322,776,678,406,322,776,314,778,678,406,678,406,314,776,314,776,680,404,680,404,12140,6686,4794,1492,316,776,678,404,316,776,678,406,314,778,678,456,262,832,624,408,316,778,678,404,314,778,678,406,314,782,678,406,316,776,678,406,320,778,678,404,236,856,678,406,314,778,678,404,316,776,680,404,322,778,678,404,314,776,684,404,316,776,678,406,314,776,680,404,322,776,314,776,678,406,678,404,316,776,316,776,678,404,678,406","protocol_name":"Raw","repeat":10,"bits":126}'
    payload_off: '{"raw":"6662,4814,1492,314,778,678,404,314,778,684,406,314,778,678,404,314,778,678,406,318,778,678,406,312,778,678,406,314,778,678,406,314,778,678,406,320,776,678,406,320,776,678,430,288,778,678,406,314,778,678,406,320,778,678,406,314,778,678,406,314,778,678,406,314,778,678,404,322,776,320,778,314,778,678,404,316,778,314,778,314,780,674,406,12138,6662,4816,1492,322,776,678,404,314,778,678,406,314,778,678,406,314,778,676,406,318,778,678,406,314,776,678,406,314,778,678,406,314,778,684,406,320,776,678,406,314,776,678,406,314,778,678,404,314,778,678,406,322,776,678,430,290,776,676,406,314,776,678,408,320,776,678,404,322,778,314,778,314,778,678,404,314,778,314,778,314,776,678,406,12140,6660,4820,1494,314,778,678,406,312,778,678,406,314,778,678,406,314,778,680,404,318,778,678,406,314,778,678,406,320,776,676,406,314,778,678,406,320,776,678,406,314,776,680,404,314,778,678,404,316,778,678,404,322,776,678,404,314,778,682,406,314,778,678,404,314,778,676,406,322,776,314,778,314,778,678,406,314,778,314,778,314,776,678,406","protocol_name":"Raw","repeat":10,"bits":126}'
    optimistic: false
    retain: false
```

**System Informations:**
 - Device: Deebot ozmo T8
 - Home Assistant Version: core-2021.6.5
 - Hardware: Raspberry Pi
 - Home Assistant Installation: Linux, supervisor-2021.06.3

**Additional context**
I think it may be related to this [issue](https://community.home-assistant.io/t/failed-login/203359 ) 
If anyone else is having the same issue disabling the map fixes it.

**Logs**
No log when filtered on [deebotozmo]
