### ISSUE TITLE
Spot Cleaning Script

### ISSUE THREAD

**Issue by timothylarson** [And3rsL/Deebot-for-Home-Assistant#144]
I don't fully understand how to create a script to make the buttons in the toolbar of the vacuum card work.

I assume I need to create a script named something like "CLEAN_LIVINGROOM" and enter the example code you provided, but I get an error saying "Message malformed: extra keys not allowed @ data['sequence'][0]['command']"

What's the best way to create a script to clean a specific room?

<img width="565" alt="Screen Shot 2021-06-22 at 1 04 16 PM" src="https://user-images.githubusercontent.com/10687886/122991921-6d590500-d35a-11eb-9e67-01b67bc59de2.png">

**Comment by illivanillie** [comment]
Try this:
```
sequence:
  - service: vacuum.send_command
    target:
      entity_id: vacuum.name
    data:
      command: custom_area
      params:
        rooms
        cleanings: 
```
Actually the visual editor is working with this, try it.
