### ISSUE TITLE
can't find my deebot t8 max

### ISSUE THREAD

**Issue by horacecar** [And3rsL/Deebot-for-Home-Assistant#146]
**Describe the bug**

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: cn
    continent: ww
    deviceid: YOUR_ROBOT_ID
```

**Screenshots**

**System Informations:**
 - Device: [Deebot ozmo 950][.. 960][.. 920]
 - Home Assistant Version: 0.110.0 ...
 - Hardware: Raspberry,NAS, etc..
 - Home Assistant Installation: Windows/Linux

**Additional context**

**Logs**
Please add full home_assistant.log filtered on [deebotozmo]
